# -*- mode: python ; coding: utf-8 -*-
# RetryClicker.spec — PyInstaller build spec for macOS .app bundle
# Run:  pyinstaller RetryClicker.spec

import sys, os

block_cipher = None

a = Analysis(
    ['retry_clicker.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        # Bundle the templates folder (may be empty on first run — that's fine)
        ('templates', 'templates'),
    ],
    hiddenimports=[
        'PIL._tkinter_finder',
        'pytesseract',
        'mss',
        'mss.darwin',
        'cv2',
        'numpy',
        'pyautogui',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'scipy', 'pandas', 'jupyter'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='RetryClicker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,          # no terminal window
    disable_windowed_traceback=False,
    argv_emulation=True,    # needed for macOS .app
    target_arch=None,       # universal2 handled by build_mac_app.sh
    codesign_identity=None,
    entitlements_file='entitlements.plist',
    icon='AppIcon.icns',    # generated by build script if present
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='RetryClicker',
)

app = BUNDLE(
    coll,
    name='RetryClicker.app',
    icon='AppIcon.icns',
    bundle_identifier='com.retryclicker.app',
    version='1.0.0',
    info_plist={
        # ── Identity
        'CFBundleName':              'RetryClicker',
        'CFBundleDisplayName':       'RetryClicker',
        'CFBundleIdentifier':        'com.retryclicker.app',
        'CFBundleVersion':           '1.0.0',
        'CFBundleShortVersionString':'1.0.0',
        'CFBundleExecutable':        'RetryClicker',
        'CFBundlePackageType':       'APPL',
        'CFBundleSignature':         '????',

        # ── macOS Tahoe / Sequoia / Sonoma required keys
        'NSScreenCaptureUsageDescription':
            'RetryClicker needs screen access to detect and click buttons automatically.',
        'NSAppleEventsUsageDescription':
            'RetryClicker uses Apple Events to send clicks.',

        # ── Accessibility (used by pyautogui to click)
        'NSAppleScriptEnabled': False,

        # ── Dock / launch behaviour
        'LSUIElement': False,            # shows in Dock
        'LSMinimumSystemVersion': '14.0',
        'NSHighResolutionCapable': True,
        'NSRequiresAquaSystemAppearance': False,  # supports dark mode

        # ── Tkinter / window server
        'NSPrincipalClass': 'NSApplication',

        # ── Privacy — suppress macOS 15+ prompts
        'NSCameraUsageDescription': '',
        'NSMicrophoneUsageDescription': '',
    },
)
